const preguntas = [
  { titulo: "Me resulta difícil hablar frente a un grupo." },
  { titulo: "Me gustaría nacer de nuevo y ser diferente de cómo ahora soy yo." },
  { titulo: "Me siento seguro de mí mismo en la mayoría de las situaciones." },
  { titulo: "Frente a varias dificultades que tengo las intento solucionar una por una." },
  { titulo: "Soy una persona popular entre los chicos y chicas de mi edad." },
  { titulo: "Hay muchas cosas dentro de mí que cambiaría si pudiera (mi carácter, mi manera de contestar, etc.)" },
  { titulo: "Ante un problema me pongo nervioso y no sé cómo enfrentarlo." },
  { titulo: "Considero que soy una persona alegre y feliz." },
  { titulo: "Si me molesto con alguien se lo digo." },
  { titulo: "Pienso que mi vida es muy triste." },
  { titulo: "Soy optimista (pienso que todo me va a salir bien) en todo lo que hago." },
  { titulo: "Confío en que frente a un problema sabré cómo darle solución." },
  { titulo: "Me resulta fácil hacer amigos." },
  { titulo: "Tengo una mala opinión de mí mismo." },
  { titulo: "Antes de resolver un problema, primero pienso cómo lo haré." },
  { titulo: "Estoy descontento con la vida que tengo." },
  { titulo: "Mis amigos confían bastante en mí." },
  { titulo: "Pienso que soy una persona fea comparada con otras(os)." },
  { titulo: "Al solucionar un problema cometo muchos errores." },
  { titulo: "Rápidamente me pongo triste por cualquier cosa." },
  { titulo: "Me siento contento(a) con casi todos mis amigos(as)." },
  { titulo: "Creo que tengo más defectos que cualidades." },
  { titulo: "Cuando intento hacer algo pienso que voy a fracasar." },
  { titulo: "Para resolver un problema que tengo me doy cuenta rápido de la solución." },
  { titulo: "Me da cólera y tengo ganas de explotar cuando no me salen las cosas como yo quiero." },
  { titulo: "Los demás son más inteligentes que yo." },
  { titulo: "Me es difícil decidirme por la solución de un problema que tengo." },
  { titulo: "Me tengo rabia y cólera a mí mismo." },
  { titulo: "Me resulta difícil relacionarme con los demás." },
  { titulo: "Me molesta que los demás sean mejores que yo." },
  { titulo: "Tengo bastantes amigos(as) que me buscan y me aprecian." },
  { titulo: "Yo me sé controlar cuando los profesores me llaman la atención." },
  { titulo: "Si un compañero me insulta yo voy y le hago lo mismo." },
  { titulo: "Tomar decisiones es difícil para mí." },
  { titulo: "Me pongo nervioso(a) si los profesores me hacen una pregunta en la clase." },
  { titulo: "Me llevo bien con la gente en general." },
  { titulo: "Soy una persona que confía en lo que hace." },
  { titulo: "Me siento feliz y estoy contento con mi cuerpo." },
  { titulo: "Los demás opinan que soy una persona sociable (tengo amistades, estoy en grupo, participo con los demás)." },
  { titulo: "Sé que mantengo la calma frente a los problemas que son difíciles." },
];

export default preguntas;